#!/bin/bash

set -x

echo =======================================
echo pwd
pwd

echo =======================================
echo mount
mount

echo =======================================
echo ls -al /snap/contentconsumer/current/data/
ls -al /snap/contentconsumer/current/data-c/

